Update hagfish-watcher to support sub-minute metering
TritonDataCenter/sdc-hagfish-watcher pull request #33
Opened 2023-07-28 14:13 UTC by marsell

Some users create very short-lived VMs (especially using Docker), which `hagfish-watcher` misses. If a VM lifetime is notably shorter than one minute, `hagfish-watcher` is likely to not notice the VM ever existing due to polling every 60s. This is particularly a problem if attempting to use hagfish results for later generating usage and/or billing: a lot of VMs fly under the radar.

This is a minimally-invasive change that makes `hagfish-watcher` check for VMs every 15s instead of every 60, but continues to write out results every 60s. It does this by maintaining an internal cache that is written to every 15s, and written (and cleared) to disk every 60s. This may not be the most elegant change, but it should minimize risk.

The main danger of checking VM status more often is querying ZFS more often, especially when there are huge numbers of VMs or snapshots. Luckily, `hagfish-watcher` already contains a mechanism so that it will not create new queries before existing ones complete. Looking at `vfsstat` and `zfs iostat` (just to be safe), I observe minimal difference when `hagfish-watcher` is doing 12-20s queries on a server with 32K snapshots every 60s versus every 5s:

```
[root@e4-43-4b-86-6c-08 (ro-1) ~]# zpool iostat 120
              capacity     operations     bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
...
60s _resched():
zones       20.9T  3.11T      0    738    153  4.15M
zones       20.9T  3.11T      1    854    738  4.86M
zones       20.9T  3.11T      0    862  1.54K  5.06M
...
15s _resched():
zones       20.9T  3.11T      0    635    166  3.68M
zones       20.9T  3.11T      0    673     59  4.19M
zones       20.9T  3.11T      0    743  1.25K  4.58M
...
5s _resched():
zones       20.9T  3.11T      2    850  3.06K  4.49M
zones       20.9T  3.11T      3   1008  9.68K  5.23M
zones       20.9T  3.11T      6  1.00K  8.38K  5.69M

[root@e4-43-4b-86-6c-08 (ro-1) ~]# vfsstat 120
  r/s   w/s  kr/s  kw/s ractv wactv read_t writ_t  %r  %w   d/s  del_t zone
...
60s _resched():
 14.3   5.2  41.2   3.1   0.0   0.0    3.7    6.1   0   0   0.0    0.0 global (0)
 34.9   3.5  54.9   0.9   0.0   0.0    2.2    9.4   0   0   0.0    0.0 global (0)
 28.4   3.3  32.7   0.9   0.0   0.0    2.3    9.1   0   0   0.0    0.0 global (0)
...
15s _resched():
 56.0   5.6  62.9   1.5   0.0   0.0    2.0    9.5   0   0   0.0    0.0 global (0)
  9.6   1.6  38.8   0.4   0.0   0.0    4.6   14.2   0   0   0.0    0.0 global (0)
 32.5   5.3  34.5   1.2   0.0   0.0    2.2   10.0   0   0   0.0    0.0 global (0)
...
5s _resched():
 56.4   5.8  49.6   1.5   0.0   0.0    8.0   11.5   0   0   0.0    0.0 global (0)
 11.3   2.0  35.5   0.3   0.0   0.0    4.4   16.1   0   0   0.0    0.0 global (0)
 40.4   5.6  60.4   1.2   0.0   0.0    2.1   11.2   0   0   0.0    0.0 global (0)
```

This patch has been used in production, although I've made some minor cleanups since then.

2023-07-31 13:56 UTC, danmcd reviewed
1.) One nit keeps me from +1-ing this.

2.) I'd like @bahamat to review this too.

3.) We should probably file a TRITON- tracking bug for bookkeeping.

4.) Used-in-production is pretty good testing, but you mention some cleanup.  What part of this is "cleanup" and is it worthy of further testing, or is it, say, editorial/comments?

2023-07-31 13:56 UTC, danmcd commented on lib/service.js
> +    var writeOut = dt.getUTCSeconds() === 0;
Readability nit:  can/should you put the boolean in parens, i.e. `(dt.GetUTCSeconds() === 0)` ?

2023-07-31 16:05 UTC, bahamat commented
Ok, I haven’t extensively reviewed the change yet, but two things right off the bat:

1. All commits must reference an issue ID. So create an issue (here in GitHub is ok) for the requested change and we can reference the issue in the final commit message.
2. I’d like this gated behind a SAPI setting. Since this introduces a change in how billing is performed, some customers may unexpectedly start getting charged more. Not all cloud providers will be ok with this. At Joyent when we introduced docker we told customers that an instance that couldn’t survive for at least 1m wouldn’t be charged. Some people were worried about VMs that unexpectedly exit too early. Having a SAPI setting will allow providers to set a value that works best for their business and customers, but for others it will continue to behave as-is when upgrading.

2023-07-31 16:06 UTC, bahamat requested changes
Require sapi setting.

2023-08-05 15:38 UTC, marsell commented
Adding a sapi setting is sane, but hagfish-watcher doesn't seem to leverage sapi much. I'm used to dealing with sapi_manifests/*/template, but there's none of that here; should I add support for it?

2023-11-03 18:37 UTC, bahamat requested changes
Ok, there's two things about this:

1. kstat needs to be locked to `"1.0.2"` instead of `"^1.0.2"`. We updated kstat to 1.1.0, which breaks on the old version of node being used. (alternatively, you could try getting hagfish to build with node v6)
2. The updated files need the copyright notice updated. Using your own company name is best, but you can alternatively use `2023 MNX Cloud, Inc.` instead.

2023-11-10 09:30 UTC, marsell commented
Added both changes @bahamat requested, the one code change @danmcd requested, and bumped hagfish version from 1.0.1 to 1.1.0.

2023-11-14 15:39 UTC, danmcd approved these changes
I also put your testing notes into the ticket, since you can't.  :)

2023-11-14 17:00 UTC, bahamat requested changes

2023-11-14 17:00 UTC, bahamat commented on lib/service_gzip.js
This file needs copyright notice.

2023-11-14 17:00 UTC, bahamat commented on lib/service_usage.js
This file needs copyright notice.

2023-11-14 18:39 UTC, danmcd approved these changes

2023-11-15 17:36 UTC, merged